# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainwatch < Formula
  desc "Enforcement runtime for autonomous AI agents"
  homepage "https://chainwatch.dev"
  version "1.7.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obstalabs/chainwatch-dist/releases/download/v1.7.0/chainwatch_1.7.0_darwin_amd64.tar.gz"
      sha256 "b52512107741a233ca64a177e67ae7656bd5c4bcf483d6439116871c95580b6c"

      define_method(:install) do
        bin.install "chainwatch"
        bin.install "nullbot"
        bin.install "sentinel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obstalabs/chainwatch-dist/releases/download/v1.7.0/chainwatch_1.7.0_darwin_arm64.tar.gz"
      sha256 "fcfb107c06bb82c5d42ae0d2e356409273b9ec76ff9099d718aa69730c18efa8"

      define_method(:install) do
        bin.install "chainwatch"
        bin.install "nullbot"
        bin.install "sentinel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/chainwatch-dist/releases/download/v1.7.0/chainwatch_1.7.0_linux_amd64.tar.gz"
      sha256 "5b8b780d48d4618aa91813f27946bb3ded567935e16f929913732eec12b02f3f"
      define_method(:install) do
        bin.install "chainwatch"
        bin.install "nullbot"
        bin.install "sentinel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/chainwatch-dist/releases/download/v1.7.0/chainwatch_1.7.0_linux_arm64.tar.gz"
      sha256 "4cf1144ab15c8329d84cb71991b5513b760182ad73d3663ec54b866be677a4bf"
      define_method(:install) do
        bin.install "chainwatch"
        bin.install "nullbot"
        bin.install "sentinel"
      end
    end
  end

  test do
    system "#{bin}/chainwatch", "version"
  end
end
