# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hivebus < Formula
  desc "Secure threaded coordination bus for agents"
  homepage "https://github.com/obstalabs/hivebus"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obstalabs/hivebus/releases/download/v0.3.2/hivebus_0.3.2_darwin_amd64.tar.gz"
      sha256 "301b59328d2227b6ce9d40aeaab70e3c5f4054fe7f62c977ccd7f0a63a9fdb57"

      def install
        bin.install "hivebus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obstalabs/hivebus/releases/download/v0.3.2/hivebus_0.3.2_darwin_arm64.tar.gz"
      sha256 "f7b404a9cb92cc7a7f298d241cfe757924520214187095086047fc683a81ccd8"

      def install
        bin.install "hivebus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/hivebus/releases/download/v0.3.2/hivebus_0.3.2_linux_amd64.tar.gz"
      sha256 "b5c91b815959bbe15c67c7857d2da5f10665f3dd26cb1014b2413f3618d594b7"
      def install
        bin.install "hivebus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/hivebus/releases/download/v0.3.2/hivebus_0.3.2_linux_arm64.tar.gz"
      sha256 "f47d4aed7f8a6c0bde77d55780926b7086e5109c18b6e4ea664187ecb27ae971"
      def install
        bin.install "hivebus"
      end
    end
  end

  test do
    system "#{bin}/hivebus", "version"
  end
end
