# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neurorouter < Formula
  desc "LLM proxy that cleans, protects, and stabilizes AI sessions before they hit the model"
  homepage "https://neurorouter.dev"
  version "0.1.7"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obstalabs/neurorouter/releases/download/v0.1.7/neurorouter_0.1.7_darwin_amd64.tar.gz"
      sha256 "b43aa63e0b4e377206e195069257475b34908254dbc86ca47627fd20d1be7742"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obstalabs/neurorouter/releases/download/v0.1.7/neurorouter_0.1.7_darwin_arm64.tar.gz"
      sha256 "55abfc2225f2056766738386d5c3e1f3c5fc8f1e47ce9832033cc2551e84266f"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/neurorouter/releases/download/v0.1.7/neurorouter_0.1.7_linux_amd64.tar.gz"
      sha256 "71743944ec506549c807d40e79c10966fc345d8aff08833aa5428f03ebe8618c"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/neurorouter/releases/download/v0.1.7/neurorouter_0.1.7_linux_arm64.tar.gz"
      sha256 "d3c17ca2200bf17462982591c7ec922ba334f31ba033d8ebd2b598e85882631f"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  test do
    system "#{bin}/neurorouter", "version"
  end
end
