# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeurorouterPro < Formula
  desc "LLM proxy that keeps AI sessions alive — multiplexing, continuity repair, model routing"
  homepage "https://neurorouter.dev"
  version "0.17.14"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.17.14/neurorouter-pro_0.17.14_darwin_amd64.tar.gz"
      sha256 "e593c98e52ae0ea350e57fbd64eb44d121c47183e9789290c9f76bbafeba7f52"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.17.14/neurorouter-pro_0.17.14_darwin_arm64.tar.gz"
      sha256 "18df1a8ac5c8d4a0b361f2f89b5a7e548f718dc6212f9f4e93717ad77e4cd616"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.17.14/neurorouter-pro_0.17.14_linux_amd64.tar.gz"
      sha256 "696c3f597c166f9a614fbfe1b9e1d9ad2565223e32ee1251acc42b54d4092174"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.17.14/neurorouter-pro_0.17.14_linux_arm64.tar.gz"
      sha256 "af6542973781f9cc1c81e67e8344eef32c162a13309ba9207d55590c2de8963e"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  test do
    system "#{bin}/neurorouter", "version"
  end
end
