# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeurorouterPro < Formula
  desc "LLM proxy that keeps AI sessions alive — multiplexing, continuity repair, model routing"
  homepage "https://neurorouter.dev"
  version "0.18.27"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.18.27/neurorouter-pro_0.18.27_darwin_amd64.tar.gz"
      sha256 "a26d10113b7e244322dbab4301cba2c574ceec5a86e2448806d00915287a2cb6"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.18.27/neurorouter-pro_0.18.27_darwin_arm64.tar.gz"
      sha256 "63614c690c445ee4400e888fee68b997944fbd7143cd3c7c66f8a7b5ac0681c1"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.18.27/neurorouter-pro_0.18.27_linux_amd64.tar.gz"
      sha256 "edc4e8a5b9b468fdd551f68cc8c4c2cc06b18106636ab483683fc23eb4867df5"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/neurorouter-pro-dist/releases/download/v0.18.27/neurorouter-pro_0.18.27_linux_arm64.tar.gz"
      sha256 "3b0eaecc877d7b8904db56d134c8380633b224d3945fa8a2c13426ae02f04b06"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  test do
    system "#{bin}/neurorouter", "version"
  end
end
