# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verdict < Formula
  desc "Enforcement runtime for autonomous AI agents"
  homepage "https://obstalabs.dev/verdict"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obstalabs/verdict-dist/releases/download/v0.1.0/verdict_0.1.0_darwin_amd64.tar.gz"
      sha256 "76b2058d47b16763646eeabf29270fb230837a2507a6ad9cc36a921da3d09d7a"

      define_method(:install) do
        bin.install "verdict"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obstalabs/verdict-dist/releases/download/v0.1.0/verdict_0.1.0_darwin_arm64.tar.gz"
      sha256 "3bb0f98ba46555a922206ab683128e38d8630e7abb5f52dc18e94186eee6c3dd"

      define_method(:install) do
        bin.install "verdict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/verdict-dist/releases/download/v0.1.0/verdict_0.1.0_linux_amd64.tar.gz"
      sha256 "fa72ae354aebf4c136f0ee23ed85314cc5ee1967753b74f3d544d99faed7bd62"
      define_method(:install) do
        bin.install "verdict"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obstalabs/verdict-dist/releases/download/v0.1.0/verdict_0.1.0_linux_arm64.tar.gz"
      sha256 "6eaa6477998c45e8a3f2f53d17b2571d293709dd5bf02ee47c59f35c08dee2cb"
      define_method(:install) do
        bin.install "verdict"
      end
    end
  end

  test do
    system "#{bin}/verdict", "version"
  end
end
