# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workledger < Formula
  desc "Hiveram ledger plane for work orders, claims, release bundles, and WEO attribution"
  homepage "https://hiveram.com"
  version "0.55.21"

  host_cpu = RbConfig::CONFIG.fetch("host_cpu", "")
  host_arm = Hardware::CPU.arm? || host_cpu.match?(/arm|aarch64/i)
  host_intel = Hardware::CPU.intel? || host_cpu.match?(/x86_64|amd64/i)

  if OS.mac?
    if host_arm
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.55.21/workledger_0.55.21_darwin_arm64.tar.gz"
      sha256 "5d300cba840ae505020a49f9997c007ae72e8e1800d79493fcf1e1d24d1a98bf"
    elsif host_intel
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.55.21/workledger_0.55.21_darwin_amd64.tar.gz"
      sha256 "d95c5f1203d472e8f24a00f6a5a22f452969e5ed6d73adc8a128128ffc04c7ef"
    else
      raise "unsupported macOS CPU: #{host_cpu}"
    end
  elsif OS.linux?
    if host_arm
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.55.21/workledger_0.55.21_linux_arm64.tar.gz"
      sha256 "28286a20099bf89b2f4844a20302681066f722732d8e2926d65e82c7e77e905a"
    elsif host_intel
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.55.21/workledger_0.55.21_linux_amd64.tar.gz"
      sha256 "2208491e69d7d8f69bacd4a50901cd0b1cdba6343967ab03ab225df8af855a39"
    else
      raise "unsupported Linux CPU: #{host_cpu}"
    end
  end

  def install
    bin.install "workledger"
  end

  test do
    system "#{bin}/workledger", "version"
  end
end
