# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workledger < Formula
  desc "Hiveram ledger plane for work orders, claims, release bundles, and WEO attribution"
  homepage "https://hiveram.com"
  version "0.16.2"

  on_macos do
    on_intel do
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.16.2/workledger_0.16.2_darwin_amd64.tar.gz"
      sha256 "0a1798796a1a9270188ebaf073b5440b4a945b80ae99efaaa7139e74c5185e49"
    end

    on_arm do
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.16.2/workledger_0.16.2_darwin_arm64.tar.gz"
      sha256 "873b88d57ea6a63b19094c49b4c7b6e8d88df984c810b5b8c12d2fe361dd20ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.16.2/workledger_0.16.2_linux_amd64.tar.gz"
      sha256 "70c214f73359fd4749038e59951fd3acfb8fb8bc6773d0559e3f18bf66411246"
    end

    on_arm do
      url "https://github.com/obstalabs/hiveram-dist/releases/download/v0.16.2/workledger_0.16.2_linux_arm64.tar.gz"
      sha256 "1a0922f770e52fc903c6d77d4b73378d4cc78a34da971f8249a755d1cb103e62"
    end
  end

  def install
    bin.install "workledger"
  end

  test do
    system "#{bin}/workledger", "version"
  end
end
